dbaux/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^functional/(?P<functional_id>\d+)/$', views.call_procedure, name='functional'),
    url(r'^system_config/list/(?P<object_type>\d+)/$', views.system_config_list, name='list'),
    url(r'^system_config/add/(?P<object_type>\d+)/$', views.system_config_add, name='add'),
    url(r'^system_config/delete/(?P<object_type>\d+)/(?P<id>\d+)/$', views.system_config_delete, name='delete'),
    url(r'^system_config/edit/(?P<object_type>\d+)/(?P<id>\d+)/$', views.system_config_edit, name='edit'),
    url(r'^system_config/detail/(?P<object_type>\d+)/(?P<id>\d+)/$', views.system_config_detail, name='detail'),
    url(r'^system_config/procedures/$', views.get_procedure_by_connection_info_id, name='procedures'),
]

urls.py
# -*- coding: utf-8 -*-
"""
urls config
"""
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
# admin.autodiscover()
from django.conf import settings

# 公共URL配置
urlpatterns = patterns(
    '',
    # Django后台数据库管理
    url(r'^admin/', include(admin.site.urls)),
    # 用户登录鉴权--请勿修改
    url(r'^account/', include('account.urls')),
    # 应用功能开关控制--请勿修改
    url(r'^app_control/', include('app_control.urls')),
    # 数据库辅助系统
    url(r'^dbaux/', include('dbaux.urls', namespace='dbaux')),
)


handler404 = 'error_pages.views.error_404'
handler500 = 'error_pages.views.error_500'
handler403 = 'error_pages.views.error_403'
handler401 = 'error_pages.views.error_401'

dbaux/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class ConnectionInfo(models.Model):
    """数据库连接信息"""
    name = models.CharField(u'名称', max_length=30, null=False)
    host = models.GenericIPAddressField(u'数据库主机')
    port = models.IntegerField(u'端口', default=3306)
    user = models.CharField(u'用户名', max_length=30)
    password = models.CharField(u'密码', max_length=40)
    database = models.CharField(u'数据库', max_length=20)
    charset = models.CharField(u'连接字符集', max_length=20, default='utf8')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]
        unique_together = (("name",), ("host", "port", "user", "database"),)


class StorageRegistry(models.Model):
    """存储过程注册信息"""
    name = models.CharField(u'名称', max_length=30, null=False)
    description = models.CharField(u'描述', max_length=100)
    storage_name = models.CharField(u'存储过程名称', max_length=100)
    connection_info = models.ForeignKey(ConnectionInfo, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["id"]
        unique_together = (("name",), ("storage_name", "connection_info"),)


class StorageArgument(models.Model):
    """存储过程参数信息"""
    index = models.IntegerField(u'参数顺序')
    name = models.CharField(u'参数名称', max_length=30, null=False)
    description = models.CharField(u'参数说明', max_length=100)
    storage = models.ForeignKey(StorageRegistry, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["storage", "index"]
        unique_together = (("name",), ("storage", "index"),)


class History(models.Model):
    '''操作历史'''
    operator = models.CharField(u'操作用户', max_length=30)
    info = models.CharField(u'操作信息', max_length=300)
    time = models.DateTimeField(u'时间', auto_now=True)

dbaux/views.py
# -*- coding: utf-8 -*-

import json
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from common.mymako import render_mako_context
from django.http import HttpResponse
# from django.shortcuts import render
from django.template import loader
from django.db.models import ObjectDoesNotExist
from .models import ConnectionInfo, StorageRegistry
from . import dbhelper

# Create your views here.
"""
允许的操作
1: 操作 ConnectionInfo
2: 操作 StorageRegistry
"""
ALLOWED_OBJECT_TYPES = ("1", "2")
"""
允许的操作方法
list: 获取对象列表
add: 添加
delete: 删除
edit: 修改
"""
ALLOWED_ACTIONS = ("list", "add", "delete", "edit")


@require_GET
def index(request):
    """
    首页界面展示
    """
    content = {
        'items': StorageRegistry.objects.all(),
    }
    return render_mako_context(request, '/dbaux/index.html', content)


@require_GET
def system_config_list(request, object_type):
    """
    获取配置列表
    """
    illegal_error_message = u'不合法的操作'
    response = {}

    if object_type not in ALLOWED_OBJECT_TYPES:
        response['result'] = False
        response['message'] = illegal_error_message
        return HttpResponse(response)

    if object_type == "1":
        """获取 ConnectionInfo 配置列表"""
        obj = ConnectionInfo
        title = '添加数据库连接'
        template_file = 'dbaux/connection_info_list_tmpl.html'
        response['result'] = True
    elif object_type == "2":
        """获取 StorageRegistry 配置列表"""
        obj = StorageRegistry
        title = '注册存储过程'
        template_file = 'dbaux/storage_list_tmpl.html'
        response['result'] = True
    else:
        response['result'] = False
        response['message'] = illegal_error_message

    if response['result']:
        items = obj.objects.all()
        content = {
            'title': title,
            'object_type': object_type,
            'items': items,
        }
        t = loader.get_template(template_file)
        response['data'] = t.render(content, request)

    return HttpResponse(json.dumps(response))


@require_http_methods(['GET', 'POST'])
def system_config_add(request, object_type):
    """
    添加配置
    """
    illegal_error_message = u'不合法的操作'
    response = {}

    if object_type not in ALLOWED_OBJECT_TYPES:
        response['result'] = False
        response['message'] = illegal_error_message
        return HttpResponse(response)

    if request.method == "GET":
        items = obj = None
        if object_type == "1":
            """添加 ConnectionInfo"""
            title = '添加数据库连接'
            template_file = 'dbaux/connection_info_add_tmpl.html'
            response['result'] = True
        elif object_type == "2":
            """添加 StorageRegistry"""
            obj = ConnectionInfo  # 供添加页面选择配置的数据库连接
            title = '注册存储过程'
            template_file = 'dbaux/storage_add_tmpl.html'
            response['result'] = True
        else:
            response['result'] = False
            response['message'] = illegal_error_message

        if response['result']:
            items = obj.objects.all() if obj else None
            content = {
                'title': title,
                'object_type': object_type,
                'items': items,
            }
            t = loader.get_template(template_file)
            response['data'] = t.render(content, request)

        return HttpResponse(json.dumps(response))
    elif request.method == "POST":
        if object_type == "1":
            """添加 ConnectionInfo"""
            name = request.POST['name'].replace('&nbsp;', ' ')
            host = request.POST['host']
            port = int(request.POST['port'])
            user = request.POST['user']
            password = request.POST['password']
            database = request.POST['database']
            charset = request.POST['charset']
            ConnectionInfo.objects.create(name=name, host=host, port=port, user=user, password=password,
                                          database=database, charset=charset)
            response['result'] = True
        elif object_type == "2":
            """添加 StorageRegistry"""
            connection_info_id = int(request.POST['connection_info_id'])
            name = request.POST['name'].replace('&nbsp;', ' ')
            description = request.POST['description'].replace('&nbsp;', ' ')
            storage_name = request.POST['storage_name']
            args = json.loads(request.POST['args'])

            try:
                connection_info = ConnectionInfo.objects.get(id=connection_info_id)
                storage = connection_info.storageregistry_set.create(name=name, description=description,
                                                                     storage_name=storage_name)
                for arg_index in ["%s" % i for i in range(1, len(args) + 1)]:
                    for k, v in args[arg_index].items():
                        storage.storageargument_set.create(index=arg_index, name=k, description=v.replace('&nbsp;', ' '))
                        break
                response['result'] = True
            except ObjectDoesNotExist:
                response['result'] = False
                response['message'] = u'添加失败：指定的数据库连接不存在！'
        else:
            response['result'] = False
            response['message'] = illegal_error_message

        return HttpResponse(json.dumps(response))


@require_POST
def system_config_delete(request):
    pass


@require_http_methods(['GET', 'POST'])
def system_config_edit(request):
    pass


@require_GET
def system_config_detail(request, object_type, id):
    """
    根据对象类型和id获取详细信息
    object_type: 允许进行操作的对象类型
    id: 要操作的对象ID
    """
    illegal_error_message = u'不合法的操作'
    response = {}
    obj = None

    if object_type not in ALLOWED_OBJECT_TYPES:
        response['result'] = False
        response['message'] = illegal_error_message
        return HttpResponse(response)

    if object_type == "1":
        """获取 ConnectionInfo 配置列表"""
        obj = ConnectionInfo
        title = '数据库连接'
        template_file = 'dbaux/connection_info_detail_tmpl.html'
        response['result'] = True
    elif object_type == "2":
        """获取 StorageRegistry 配置列表"""
        obj = StorageRegistry
        title = '存储过程'
        template_file = 'dbaux/storage_detail_tmpl.html'
        response['result'] = True
    else:
        response['result'] = False
        response['message'] = illegal_error_message

    if response['result']:
        item = obj.objects.get(id=id)
        content = {
            'title': title,
            'object_type': object_type,
            'id': id,
            'item': item,
        }
        t = loader.get_template(template_file)
        response['data'] = t.render(content, request)

    return HttpResponse(json.dumps(response))


@require_http_methods(["GET", "POST"])
def call_procedure(request, functional_id):
    """
    操作执行接口，调用存储过程
    functional_id: 注册的存储过程ID
    args: 从前端页面获取的存储过程参数，dict类型
    """
    response = {}
    storage_id = functional_id

    if request.method == "GET":
        template_file = 'dbaux/storage_execute_tmpl.html'
        content = {
            'item': StorageRegistry.objects.get(id=storage_id),
        }
        t = loader.get_template(template_file)
        response['data'] = t.render(content, request)
        response['result'] = True
    elif request.method == "POST":
        # operator = request.user.username
        args = json.loads(request.POST['args'])

        try:
            arg_list = []
            storage = StorageRegistry.objects.get(id=storage_id)
            expect_args = storage.storageargument_set.all()
            if len(expect_args) == len(args):
                for arg_index in ["%s" % i for i in range(1, len(args) + 1)]:
                    arg_list.append(args[arg_index])
                    # for k, v in args[arg_index].items():
                    #     arg_list.append(k)
                    #     break
            response = dbhelper.call_procedure(storage_id, arg_list)
        except ObjectDoesNotExist:
            response['result'] = False
            response['message'] = u'执行失败：该功能不存在！'

    return HttpResponse(json.dumps(response))


@require_POST
def get_procedure_by_connection_info_id(request):
    """获取指定数据库的所有存储过程"""
    # operator = request.user.username
    response = {}
    try:
        connection_info_id = request.POST['connection_info_id']
        response['result'] = True
        response['data'] = dbhelper.get_procedure_by_connection_info_id(connection_info_id)
    except ValueError:
        response['result'] = False
    return HttpResponse(json.dumps(response))

templates/dbaux/connection_info_add_tmpl.html
<!--HTML-->
<div class="row">
    <div class="col-sm-12">
        <div class="king-block king-block-bordered">
            <div class="king-block-header king-gray-light">
                <ul class="king-block-options">
                    <li>
                        <button type="button"><i class="fa fa-cog"></i></button>
                    </li>
                </ul>
                <h3 class="king-block-title">{{ title }}</h3>
            </div>
            <div class="king-block-content">
                <!-- 水平布局表单-1 Start -->
                <form class="form-horizontal" method="POST">
                    <div class="form-group">
                        <label for="inputName1" class="col-sm-3 control-label">名称：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputName1" placeholder="输入便于识别的名称">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputHostAddress1" class="col-sm-3 control-label">数据库主机：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputHostAddress1" placeholder="IP地址">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputPort1" class="col-sm-3 control-label">端口：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputPort1" placeholder="数据库服务端口">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputUserName1" class="col-sm-3 control-label">用户名：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputUserName1" placeholder="连接数据库的用户名">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword1" class="col-sm-3 control-label">密码：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputPassword1" placeholder="连接数据库的密码">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputDatabaseName1" class="col-sm-3 control-label">数据库名称：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputDatabaseName1" placeholder="">
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputCharset1" class="col-sm-3 control-label">连接字符集：</label>
                        <div class="col-sm-7">
                            <select name="" id="inputCharset1" class="form-control">
                                <option value="utf8">utf8</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-7 col-sm-offset-3">
                            <input type="button" class="king-btn king-success mr10" id="btn_add" value="添加">
                            <input type="reset" class="king-btn king-default" id="btn_cancel" value="取消">
                        </div>
                    </div>
                </form>
                <!-- 水平布局表单-1 End -->
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $(function() {
        $('#btn_add').click(function () {
            data = {
                'name': $('#inputName1').val().trim(),
                'host': $('#inputHostAddress1').val().trim(),
                'port': $('#inputPort1').val().trim(),
                'user': $('#inputUserName1').val().trim(),
                'password': $('#inputPassword1').val().trim(),
                'database': $('#inputDatabaseName1').val().trim(),
                'charset': $('#inputCharset1').val(),
            };

            $.ajax({
                "type": "POST",
                "url": window.location.pathname + "system_config/add/" + {{ object_type }} + "/",
                "data": data,
                "dataType": "json",
                "success": function (response) {
                    if(response.result) {
                        $topBar({
                            text: '操作成功！',
                            setClass: 'bg-success',
                            timeOut: 5000
                        });
                        $.get(
                            url = window.location.pathname + 'system_config/list/' + {{ object_type }} + '/',
                            function(response, textStatus){
                                if(response.result) {
                                    $("#content_14904127718185").html(response.data);
                                } else {
                                    $topBar({
                                        text: '操作失败: ' + response.message,
                                        setClass: 'bg-danger'
                                    });
                                }
                            },
                            'json');
                    } else {
                        $topBar({
                            text: '操作失败: ' + response.message,
                            setClass: 'bg-danger'
                        });
                    }
                },
            });
        });
    });
    </script>
</div>

templates/dbaux/connection_info_detail_tmpl.html
<!--HTML-->
<div class="row">
    <div class="col-sm-12">
        <div class="king-block king-block-bordered">
            <div class="king-block-header king-gray-light">
                <ul class="king-block-options">
                    <li>
                        <button type="button"><i class="fa fa-cog"></i></button>
                    </li>
                </ul>
                <h3 class="king-block-title">{{ title }} ID: {{ item.id }}</h3>
            </div>
            <div class="king-block-content">
                <!-- 水平布局表单-1 Start -->
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="inputName1" class="col-sm-3 control-label">名称：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputName1" placeholder="输入便于识别的名称" value="{{ item.name }}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputHostAddress1" class="col-sm-3 control-label">数据库主机：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputHostAddress1" placeholder="IP地址" value="{{ item.host }}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputPort1" class="col-sm-3 control-label">端口：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputPort1" placeholder="数据库服务端口" value="{{ item.port }}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputUserName1" class="col-sm-3 control-label">用户名：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputUserName1" placeholder="连接数据库的用户名" value="{{ item.user }}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword1" class="col-sm-3 control-label">密码：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputPassword1" placeholder="连接数据库的密码" value="{% if item.password %} {{ item.password }} {% else %}<空>{% endif %}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputDatabaseName1" class="col-sm-3 control-label">数据库名称：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputDatabaseName1" placeholder="" value="{{ item.database }}" disabled>
                        </div>
                        <span class="text-danger mt5 fl">*</span>
                    </div>
                    <div class="form-group">
                        <label for="inputCharset1" class="col-sm-3 control-label">连接字符集：</label>
                        <div class="col-sm-7">
                            <select name="" id="inputCharset1" class="form-control" disabled>
                                <option value="{{ item.charset }}">{{ item.charset }}</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-7 col-sm-offset-3">
                            <input type="button" class="king-btn king-success mr10" id="btn_back" value="返回">
                        </div>
                    </div>
                </form>
                <!-- 水平布局表单-1 End -->
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $(function() {
        $('#btn_back').click(function () {
            $.get(
                url = window.location.pathname + 'system_config/list/' + {{ object_type }} +'/',
                function (response, textStatus) {
                    if (response.result) {
                        $("#content_14904127718185").html(response.data);
                    } else {
                        $topBar({
                            text: '操作失败: ' + response.message,
                            setClass: 'bg-danger'
                        });
                    }
                },
                'json');
        });
    });
    </script>
</div>

templates/dbaux/connection_info_list_tmpl.html
 <div class="panel panel-default pannel-overflow panel-tables table7_demo">
<div class="panel-body panel-search-body">
    <a class="king-btn king-radius king-primary" id="btn_add" title="{{ title }}">{{ title }}</a>
</div>
<div class="panel-content">
    <!-- 带操作按钮表格-2 Start -->
    <table class="table table-header-bg table-hover mb0" id="table_demo2">
        <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>主机</th>
                <th>端口</th>
                <th>数据库</th>
                <th>用户</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% if items %}
            {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td><a href="{% url 'dbaux:detail' object_type item.id  %}">{{ item.name }}</a></td>
                <td>{{ item.host }}</td>
                <td>{{ item.port }}</td>
                <td>{{ item.user }}</td>
                <td>{{ item.database }}</td>
                <td>
                    <button class="btn btn-xs btn-primary" title="编辑">
                        <i class="glyphicon glyphicon-edit"></i>
                    </button>
                    <button class="btn btn-xs btn-danger" title="删除">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <!-- 带操作按钮表格-2 End -->
</div>
<script type="text/javascript">
    $('#table_demo2 > tbody').find('a').click(function (event) {
        $.get(
            url = $(this).attr('href'),
            function(response, textStatus){
                if(response.result) {
                    $("#content_14904127718185").html(response.data);
                } else {
                    $topBar({
                        text: '操作失败: ' + response.message,
                        setClass: 'bg-danger'
                    });
                }
            },
            'json');
        event.preventDefault();
    })

    $('#table_demo2').find('.glyphicon-remove').parent('button').click(function(){
        if(confirm('确定要删除？')){
            $(this).closest('tr').remove();
        }
    });

    $("#btn_add").click(function (e) {
        $.get(
            url = window.location.pathname + 'system_config/add/' + {{ object_type }} + '/',
            function(response, textStatus){
                if(response.result) {
                    $("#content_14904127718185").html(response.data);
                } else {
                    $topBar({
                        text: '操作失败: ' + response.message,
                        setClass: 'bg-danger'
                    });
                }
            },
            'json');
    });
</script>
</div>

templates/dbaux/storage_list_tmpl.html
 <div class="panel panel-default pannel-overflow panel-tables table7_demo">
<div class="panel-body panel-search-body">
    <a class="king-btn king-radius king-primary" id="btn_add" title="{{ title }}">{{ title }}</a>
</div>
<div class="panel-content">
    <!-- 带操作按钮表格-2 Start -->
    <table class="table table-header-bg table-hover mb0" id="table_demo2">
        <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>存储过程</th>
                <th>所属数据库</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% if items %}
            {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td><a href="{% url 'dbaux:detail' object_type item.id  %}">{{ item.name }}</a></td>
                <td><a href="{% url 'dbaux:detail' object_type item.id  %}">{{ item.storage_name }}</a></td>
                <td>{{ item.connection_info.database }}</td>
                <td>
                    <button class="btn btn-xs btn-primary" title="编辑">
                        <i class="glyphicon glyphicon-edit"></i>
                    </button>
                    <button class="btn btn-xs btn-danger" title="删除">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <!-- 带操作按钮表格-2 End -->
</div>
<script type="text/javascript">
    $('#table_demo2 > tbody').find('a').click(function (event) {
        $.get(
            url = $(this).attr('href'),
            function(response, textStatus){
                if(response.result) {
                    $("#content_14904127718185").html(response.data);
                } else {
                    $topBar({
                        text: '操作失败: ' + response.message,
                        setClass: 'bg-danger'
                    });
                }
            },
            'json');
        event.preventDefault();
    })

    $('#table_demo2').find('.glyphicon-remove').parent('button').click(function () {
        if (confirm('确定要删除？')) {
            $(this).closest('tr').remove();
        }
    });

    $("#btn_add").click(function (e) {
        $.get(
            url = window.location.pathname + 'system_config/add/' + {{ object_type }} +'/',
            function (response, textStatus) {
                if (response.result) {
                    $("#content_14904127718185").html(response.data);
                } else {
                    $topBar({
                        text: '操作失败: ' + response.message,
                        setClass: 'bg-danger'
                    });
                }
            },
            'json');
    });
</script>
</div>